/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans/index'
import { Route as AuthenticatedSaasadminIndexRouteImport } from './routes/_authenticated/saasadmin/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedAdminChatAgentIdRouteImport } from './routes/_authenticated/admin/chat/$agentId'
import { Route as AuthenticatedAdminCourseAgentsIndexRouteImport } from './routes/_authenticated/admin/course-agents/index'
import { Route as AuthenticatedAdminCourseAgentsAgentIdRouteImport } from './routes/_authenticated/admin/course-agents/$agentId'
import { Route as AuthenticatedAdminCourseAgentsConversationRouteImport } from './routes/_authenticated/admin/course-agents/conversation'
import { Route as AuthenticatedAdminCourseAgentsModelRouteImport } from './routes/_authenticated/admin/course-agents/model'
import { Route as AuthenticatedAdminCourseAgentsStateMachineRouteImport } from './routes/_authenticated/admin/course-agents/state-machine'
import { Route as AuthenticatedAdminKnowledgeIndexRouteImport } from './routes/_authenticated/admin/knowledge/index'
import { Route as AuthenticatedAdminKnowledgeKbIdRouteImport } from './routes/_authenticated/admin/knowledge/$kbId'
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin/members/index'
import { Route as AuthenticatedAdminModelsIndexRouteImport } from './routes/_authenticated/admin/models/index'
import { Route as AuthenticatedAdminUsageIndexRouteImport } from './routes/_authenticated/admin/usage/index'
import { Route as AuthenticatedSaasadminAgentsIndexRouteImport } from './routes/_authenticated/saasadmin/agents/index'
import { Route as AuthenticatedSaasadminAgentsAgentIdRouteImport } from './routes/_authenticated/saasadmin/agents/$agentId'
import { Route as AuthenticatedSaasadminAuditIndexRouteImport } from './routes/_authenticated/saasadmin/audit/index'
import { Route as AuthenticatedSaasadminKnowledgeIndexRouteImport } from './routes/_authenticated/saasadmin/knowledge/index'
import { Route as AuthenticatedSaasadminKnowledgeKbIdRouteImport } from './routes/_authenticated/saasadmin/knowledge/$kbId'
import { Route as AuthenticatedSaasadminModelsIndexRouteImport } from './routes/_authenticated/saasadmin/models/index'
import { Route as AuthenticatedSaasadminTenantsIndexRouteImport } from './routes/_authenticated/saasadmin/tenants/index'
import { Route as AuthenticatedSaasadminUsageIndexRouteImport } from './routes/_authenticated/saasadmin/usage/index'
import { Route as AuthenticatedSaasadminUsersIndexRouteImport } from './routes/_authenticated/saasadmin/users/index'
import { Route as AuthenticatedAdminCourseAgentsLeadsIndexRouteImport } from './routes/_authenticated/admin/course-agents/leads/index'
import { Route as AuthenticatedAdminCourseAgentsLeadsLeadIdRouteImport } from './routes/_authenticated/admin/course-agents/leads/$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaasadminIndexRoute =
  AuthenticatedSaasadminIndexRouteImport.update({
    id: '/saasadmin/',
    path: '/saasadmin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminChatAgentIdRoute =
  AuthenticatedAdminChatAgentIdRouteImport.update({
    id: '/admin/chat/$agentId',
    path: '/admin/chat/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsIndexRoute =
  AuthenticatedAdminCourseAgentsIndexRouteImport.update({
    id: '/admin/course-agents/',
    path: '/admin/course-agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsAgentIdRoute =
  AuthenticatedAdminCourseAgentsAgentIdRouteImport.update({
    id: '/admin/course-agents/$agentId',
    path: '/admin/course-agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsConversationRoute =
  AuthenticatedAdminCourseAgentsConversationRouteImport.update({
    id: '/admin/course-agents/conversation',
    path: '/admin/course-agents/conversation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsModelRoute =
  AuthenticatedAdminCourseAgentsModelRouteImport.update({
    id: '/admin/course-agents/model',
    path: '/admin/course-agents/model',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsStateMachineRoute =
  AuthenticatedAdminCourseAgentsStateMachineRouteImport.update({
    id: '/admin/course-agents/state-machine',
    path: '/admin/course-agents/state-machine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeIndexRoute =
  AuthenticatedAdminKnowledgeIndexRouteImport.update({
    id: '/admin/knowledge/',
    path: '/admin/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeKbIdRoute =
  AuthenticatedAdminKnowledgeKbIdRouteImport.update({
    id: '/admin/knowledge/$kbId',
    path: '/admin/knowledge/$kbId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/admin/members/',
    path: '/admin/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModelsIndexRoute =
  AuthenticatedAdminModelsIndexRouteImport.update({
    id: '/admin/models/',
    path: '/admin/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsageIndexRoute =
  AuthenticatedAdminUsageIndexRouteImport.update({
    id: '/admin/usage/',
    path: '/admin/usage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminAgentsIndexRoute =
  AuthenticatedSaasadminAgentsIndexRouteImport.update({
    id: '/saasadmin/agents/',
    path: '/saasadmin/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminAgentsAgentIdRoute =
  AuthenticatedSaasadminAgentsAgentIdRouteImport.update({
    id: '/saasadmin/agents/$agentId',
    path: '/saasadmin/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminAuditIndexRoute =
  AuthenticatedSaasadminAuditIndexRouteImport.update({
    id: '/saasadmin/audit/',
    path: '/saasadmin/audit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminKnowledgeIndexRoute =
  AuthenticatedSaasadminKnowledgeIndexRouteImport.update({
    id: '/saasadmin/knowledge/',
    path: '/saasadmin/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminKnowledgeKbIdRoute =
  AuthenticatedSaasadminKnowledgeKbIdRouteImport.update({
    id: '/saasadmin/knowledge/$kbId',
    path: '/saasadmin/knowledge/$kbId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminModelsIndexRoute =
  AuthenticatedSaasadminModelsIndexRouteImport.update({
    id: '/saasadmin/models/',
    path: '/saasadmin/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminTenantsIndexRoute =
  AuthenticatedSaasadminTenantsIndexRouteImport.update({
    id: '/saasadmin/tenants/',
    path: '/saasadmin/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminUsageIndexRoute =
  AuthenticatedSaasadminUsageIndexRouteImport.update({
    id: '/saasadmin/usage/',
    path: '/saasadmin/usage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaasadminUsersIndexRoute =
  AuthenticatedSaasadminUsersIndexRouteImport.update({
    id: '/saasadmin/users/',
    path: '/saasadmin/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsLeadsIndexRoute =
  AuthenticatedAdminCourseAgentsLeadsIndexRouteImport.update({
    id: '/admin/course-agents/leads/',
    path: '/admin/course-agents/leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCourseAgentsLeadsLeadIdRoute =
  AuthenticatedAdminCourseAgentsLeadsLeadIdRouteImport.update({
    id: '/admin/course-agents/leads/$leadId',
    path: '/admin/course-agents/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/join/$slug': typeof JoinSlugRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/saasadmin/': typeof AuthenticatedSaasadminIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/chat/$agentId': typeof AuthenticatedAdminChatAgentIdRoute
  '/admin/course-agents/$agentId': typeof AuthenticatedAdminCourseAgentsAgentIdRoute
  '/admin/course-agents/conversation': typeof AuthenticatedAdminCourseAgentsConversationRoute
  '/admin/course-agents/model': typeof AuthenticatedAdminCourseAgentsModelRoute
  '/admin/course-agents/state-machine': typeof AuthenticatedAdminCourseAgentsStateMachineRoute
  '/admin/knowledge/$kbId': typeof AuthenticatedAdminKnowledgeKbIdRoute
  '/saasadmin/agents/$agentId': typeof AuthenticatedSaasadminAgentsAgentIdRoute
  '/saasadmin/knowledge/$kbId': typeof AuthenticatedSaasadminKnowledgeKbIdRoute
  '/admin/course-agents/': typeof AuthenticatedAdminCourseAgentsIndexRoute
  '/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/admin/models/': typeof AuthenticatedAdminModelsIndexRoute
  '/admin/usage/': typeof AuthenticatedAdminUsageIndexRoute
  '/saasadmin/agents/': typeof AuthenticatedSaasadminAgentsIndexRoute
  '/saasadmin/audit/': typeof AuthenticatedSaasadminAuditIndexRoute
  '/saasadmin/knowledge/': typeof AuthenticatedSaasadminKnowledgeIndexRoute
  '/saasadmin/models/': typeof AuthenticatedSaasadminModelsIndexRoute
  '/saasadmin/tenants/': typeof AuthenticatedSaasadminTenantsIndexRoute
  '/saasadmin/usage/': typeof AuthenticatedSaasadminUsageIndexRoute
  '/saasadmin/users/': typeof AuthenticatedSaasadminUsersIndexRoute
  '/admin/course-agents/leads/$leadId': typeof AuthenticatedAdminCourseAgentsLeadsLeadIdRoute
  '/admin/course-agents/leads/': typeof AuthenticatedAdminCourseAgentsLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/join/$slug': typeof JoinSlugRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/saasadmin': typeof AuthenticatedSaasadminIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/chat/$agentId': typeof AuthenticatedAdminChatAgentIdRoute
  '/admin/course-agents/$agentId': typeof AuthenticatedAdminCourseAgentsAgentIdRoute
  '/admin/course-agents/conversation': typeof AuthenticatedAdminCourseAgentsConversationRoute
  '/admin/course-agents/model': typeof AuthenticatedAdminCourseAgentsModelRoute
  '/admin/course-agents/state-machine': typeof AuthenticatedAdminCourseAgentsStateMachineRoute
  '/admin/knowledge/$kbId': typeof AuthenticatedAdminKnowledgeKbIdRoute
  '/saasadmin/agents/$agentId': typeof AuthenticatedSaasadminAgentsAgentIdRoute
  '/saasadmin/knowledge/$kbId': typeof AuthenticatedSaasadminKnowledgeKbIdRoute
  '/admin/course-agents': typeof AuthenticatedAdminCourseAgentsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute
  '/admin/models': typeof AuthenticatedAdminModelsIndexRoute
  '/admin/usage': typeof AuthenticatedAdminUsageIndexRoute
  '/saasadmin/agents': typeof AuthenticatedSaasadminAgentsIndexRoute
  '/saasadmin/audit': typeof AuthenticatedSaasadminAuditIndexRoute
  '/saasadmin/knowledge': typeof AuthenticatedSaasadminKnowledgeIndexRoute
  '/saasadmin/models': typeof AuthenticatedSaasadminModelsIndexRoute
  '/saasadmin/tenants': typeof AuthenticatedSaasadminTenantsIndexRoute
  '/saasadmin/usage': typeof AuthenticatedSaasadminUsageIndexRoute
  '/saasadmin/users': typeof AuthenticatedSaasadminUsersIndexRoute
  '/admin/course-agents/leads/$leadId': typeof AuthenticatedAdminCourseAgentsLeadsLeadIdRoute
  '/admin/course-agents/leads': typeof AuthenticatedAdminCourseAgentsLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/join/$slug': typeof JoinSlugRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/saasadmin/': typeof AuthenticatedSaasadminIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/chat/$agentId': typeof AuthenticatedAdminChatAgentIdRoute
  '/_authenticated/admin/course-agents/$agentId': typeof AuthenticatedAdminCourseAgentsAgentIdRoute
  '/_authenticated/admin/course-agents/conversation': typeof AuthenticatedAdminCourseAgentsConversationRoute
  '/_authenticated/admin/course-agents/model': typeof AuthenticatedAdminCourseAgentsModelRoute
  '/_authenticated/admin/course-agents/state-machine': typeof AuthenticatedAdminCourseAgentsStateMachineRoute
  '/_authenticated/admin/knowledge/$kbId': typeof AuthenticatedAdminKnowledgeKbIdRoute
  '/_authenticated/saasadmin/agents/$agentId': typeof AuthenticatedSaasadminAgentsAgentIdRoute
  '/_authenticated/saasadmin/knowledge/$kbId': typeof AuthenticatedSaasadminKnowledgeKbIdRoute
  '/_authenticated/admin/course-agents/': typeof AuthenticatedAdminCourseAgentsIndexRoute
  '/_authenticated/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute
  '/_authenticated/admin/models/': typeof AuthenticatedAdminModelsIndexRoute
  '/_authenticated/admin/usage/': typeof AuthenticatedAdminUsageIndexRoute
  '/_authenticated/saasadmin/agents/': typeof AuthenticatedSaasadminAgentsIndexRoute
  '/_authenticated/saasadmin/audit/': typeof AuthenticatedSaasadminAuditIndexRoute
  '/_authenticated/saasadmin/knowledge/': typeof AuthenticatedSaasadminKnowledgeIndexRoute
  '/_authenticated/saasadmin/models/': typeof AuthenticatedSaasadminModelsIndexRoute
  '/_authenticated/saasadmin/tenants/': typeof AuthenticatedSaasadminTenantsIndexRoute
  '/_authenticated/saasadmin/usage/': typeof AuthenticatedSaasadminUsageIndexRoute
  '/_authenticated/saasadmin/users/': typeof AuthenticatedSaasadminUsersIndexRoute
  '/_authenticated/admin/course-agents/leads/$leadId': typeof AuthenticatedAdminCourseAgentsLeadsLeadIdRoute
  '/_authenticated/admin/course-agents/leads/': typeof AuthenticatedAdminCourseAgentsLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/join/$slug'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/admin/'
    | '/audit/'
    | '/plans/'
    | '/saasadmin/'
    | '/settings/'
    | '/users/'
    | '/admin/chat/$agentId'
    | '/admin/course-agents/$agentId'
    | '/admin/course-agents/conversation'
    | '/admin/course-agents/model'
    | '/admin/course-agents/state-machine'
    | '/admin/knowledge/$kbId'
    | '/saasadmin/agents/$agentId'
    | '/saasadmin/knowledge/$kbId'
    | '/admin/course-agents/'
    | '/admin/knowledge/'
    | '/admin/members/'
    | '/admin/models/'
    | '/admin/usage/'
    | '/saasadmin/agents/'
    | '/saasadmin/audit/'
    | '/saasadmin/knowledge/'
    | '/saasadmin/models/'
    | '/saasadmin/tenants/'
    | '/saasadmin/usage/'
    | '/saasadmin/users/'
    | '/admin/course-agents/leads/$leadId'
    | '/admin/course-agents/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/join/$slug'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/admin'
    | '/audit'
    | '/plans'
    | '/saasadmin'
    | '/settings'
    | '/users'
    | '/admin/chat/$agentId'
    | '/admin/course-agents/$agentId'
    | '/admin/course-agents/conversation'
    | '/admin/course-agents/model'
    | '/admin/course-agents/state-machine'
    | '/admin/knowledge/$kbId'
    | '/saasadmin/agents/$agentId'
    | '/saasadmin/knowledge/$kbId'
    | '/admin/course-agents'
    | '/admin/knowledge'
    | '/admin/members'
    | '/admin/models'
    | '/admin/usage'
    | '/saasadmin/agents'
    | '/saasadmin/audit'
    | '/saasadmin/knowledge'
    | '/saasadmin/models'
    | '/saasadmin/tenants'
    | '/saasadmin/usage'
    | '/saasadmin/users'
    | '/admin/course-agents/leads/$leadId'
    | '/admin/course-agents/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/join/$slug'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/admin/'
    | '/_authenticated/audit/'
    | '/_authenticated/plans/'
    | '/_authenticated/saasadmin/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/chat/$agentId'
    | '/_authenticated/admin/course-agents/$agentId'
    | '/_authenticated/admin/course-agents/conversation'
    | '/_authenticated/admin/course-agents/model'
    | '/_authenticated/admin/course-agents/state-machine'
    | '/_authenticated/admin/knowledge/$kbId'
    | '/_authenticated/saasadmin/agents/$agentId'
    | '/_authenticated/saasadmin/knowledge/$kbId'
    | '/_authenticated/admin/course-agents/'
    | '/_authenticated/admin/knowledge/'
    | '/_authenticated/admin/members/'
    | '/_authenticated/admin/models/'
    | '/_authenticated/admin/usage/'
    | '/_authenticated/saasadmin/agents/'
    | '/_authenticated/saasadmin/audit/'
    | '/_authenticated/saasadmin/knowledge/'
    | '/_authenticated/saasadmin/models/'
    | '/_authenticated/saasadmin/tenants/'
    | '/_authenticated/saasadmin/usage/'
    | '/_authenticated/saasadmin/users/'
    | '/_authenticated/admin/course-agents/leads/$leadId'
    | '/_authenticated/admin/course-agents/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  JoinSlugRoute: typeof JoinSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/': {
      id: '/_authenticated/saasadmin/'
      path: '/saasadmin'
      fullPath: '/saasadmin/'
      preLoaderRoute: typeof AuthenticatedSaasadminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/chat/$agentId': {
      id: '/_authenticated/admin/chat/$agentId'
      path: '/admin/chat/$agentId'
      fullPath: '/admin/chat/$agentId'
      preLoaderRoute: typeof AuthenticatedAdminChatAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/': {
      id: '/_authenticated/admin/course-agents/'
      path: '/admin/course-agents'
      fullPath: '/admin/course-agents/'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/$agentId': {
      id: '/_authenticated/admin/course-agents/$agentId'
      path: '/admin/course-agents/$agentId'
      fullPath: '/admin/course-agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/conversation': {
      id: '/_authenticated/admin/course-agents/conversation'
      path: '/admin/course-agents/conversation'
      fullPath: '/admin/course-agents/conversation'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsConversationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/model': {
      id: '/_authenticated/admin/course-agents/model'
      path: '/admin/course-agents/model'
      fullPath: '/admin/course-agents/model'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/state-machine': {
      id: '/_authenticated/admin/course-agents/state-machine'
      path: '/admin/course-agents/state-machine'
      fullPath: '/admin/course-agents/state-machine'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsStateMachineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge/': {
      id: '/_authenticated/admin/knowledge/'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge/'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge/$kbId': {
      id: '/_authenticated/admin/knowledge/$kbId'
      path: '/admin/knowledge/$kbId'
      fullPath: '/admin/knowledge/$kbId'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeKbIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/'
      path: '/admin/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/models/': {
      id: '/_authenticated/admin/models/'
      path: '/admin/models'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AuthenticatedAdminModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usage/': {
      id: '/_authenticated/admin/usage/'
      path: '/admin/usage'
      fullPath: '/admin/usage/'
      preLoaderRoute: typeof AuthenticatedAdminUsageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/agents/': {
      id: '/_authenticated/saasadmin/agents/'
      path: '/saasadmin/agents'
      fullPath: '/saasadmin/agents/'
      preLoaderRoute: typeof AuthenticatedSaasadminAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/agents/$agentId': {
      id: '/_authenticated/saasadmin/agents/$agentId'
      path: '/saasadmin/agents/$agentId'
      fullPath: '/saasadmin/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedSaasadminAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/audit/': {
      id: '/_authenticated/saasadmin/audit/'
      path: '/saasadmin/audit'
      fullPath: '/saasadmin/audit/'
      preLoaderRoute: typeof AuthenticatedSaasadminAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/knowledge/': {
      id: '/_authenticated/saasadmin/knowledge/'
      path: '/saasadmin/knowledge'
      fullPath: '/saasadmin/knowledge/'
      preLoaderRoute: typeof AuthenticatedSaasadminKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/knowledge/$kbId': {
      id: '/_authenticated/saasadmin/knowledge/$kbId'
      path: '/saasadmin/knowledge/$kbId'
      fullPath: '/saasadmin/knowledge/$kbId'
      preLoaderRoute: typeof AuthenticatedSaasadminKnowledgeKbIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/models/': {
      id: '/_authenticated/saasadmin/models/'
      path: '/saasadmin/models'
      fullPath: '/saasadmin/models/'
      preLoaderRoute: typeof AuthenticatedSaasadminModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/tenants/': {
      id: '/_authenticated/saasadmin/tenants/'
      path: '/saasadmin/tenants'
      fullPath: '/saasadmin/tenants/'
      preLoaderRoute: typeof AuthenticatedSaasadminTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/usage/': {
      id: '/_authenticated/saasadmin/usage/'
      path: '/saasadmin/usage'
      fullPath: '/saasadmin/usage/'
      preLoaderRoute: typeof AuthenticatedSaasadminUsageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saasadmin/users/': {
      id: '/_authenticated/saasadmin/users/'
      path: '/saasadmin/users'
      fullPath: '/saasadmin/users/'
      preLoaderRoute: typeof AuthenticatedSaasadminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/leads/': {
      id: '/_authenticated/admin/course-agents/leads/'
      path: '/admin/course-agents/leads'
      fullPath: '/admin/course-agents/leads/'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/course-agents/leads/$leadId': {
      id: '/_authenticated/admin/course-agents/leads/$leadId'
      path: '/admin/course-agents/leads/$leadId'
      fullPath: '/admin/course-agents/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedAdminCourseAgentsLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedSaasadminIndexRoute: typeof AuthenticatedSaasadminIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAdminChatAgentIdRoute: typeof AuthenticatedAdminChatAgentIdRoute
  AuthenticatedAdminCourseAgentsAgentIdRoute: typeof AuthenticatedAdminCourseAgentsAgentIdRoute
  AuthenticatedAdminCourseAgentsConversationRoute: typeof AuthenticatedAdminCourseAgentsConversationRoute
  AuthenticatedAdminCourseAgentsModelRoute: typeof AuthenticatedAdminCourseAgentsModelRoute
  AuthenticatedAdminCourseAgentsStateMachineRoute: typeof AuthenticatedAdminCourseAgentsStateMachineRoute
  AuthenticatedAdminKnowledgeKbIdRoute: typeof AuthenticatedAdminKnowledgeKbIdRoute
  AuthenticatedSaasadminAgentsAgentIdRoute: typeof AuthenticatedSaasadminAgentsAgentIdRoute
  AuthenticatedSaasadminKnowledgeKbIdRoute: typeof AuthenticatedSaasadminKnowledgeKbIdRoute
  AuthenticatedAdminCourseAgentsIndexRoute: typeof AuthenticatedAdminCourseAgentsIndexRoute
  AuthenticatedAdminKnowledgeIndexRoute: typeof AuthenticatedAdminKnowledgeIndexRoute
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute
  AuthenticatedAdminModelsIndexRoute: typeof AuthenticatedAdminModelsIndexRoute
  AuthenticatedAdminUsageIndexRoute: typeof AuthenticatedAdminUsageIndexRoute
  AuthenticatedSaasadminAgentsIndexRoute: typeof AuthenticatedSaasadminAgentsIndexRoute
  AuthenticatedSaasadminAuditIndexRoute: typeof AuthenticatedSaasadminAuditIndexRoute
  AuthenticatedSaasadminKnowledgeIndexRoute: typeof AuthenticatedSaasadminKnowledgeIndexRoute
  AuthenticatedSaasadminModelsIndexRoute: typeof AuthenticatedSaasadminModelsIndexRoute
  AuthenticatedSaasadminTenantsIndexRoute: typeof AuthenticatedSaasadminTenantsIndexRoute
  AuthenticatedSaasadminUsageIndexRoute: typeof AuthenticatedSaasadminUsageIndexRoute
  AuthenticatedSaasadminUsersIndexRoute: typeof AuthenticatedSaasadminUsersIndexRoute
  AuthenticatedAdminCourseAgentsLeadsLeadIdRoute: typeof AuthenticatedAdminCourseAgentsLeadsLeadIdRoute
  AuthenticatedAdminCourseAgentsLeadsIndexRoute: typeof AuthenticatedAdminCourseAgentsLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedSaasadminIndexRoute: AuthenticatedSaasadminIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAdminChatAgentIdRoute: AuthenticatedAdminChatAgentIdRoute,
  AuthenticatedAdminCourseAgentsAgentIdRoute:
    AuthenticatedAdminCourseAgentsAgentIdRoute,
  AuthenticatedAdminCourseAgentsConversationRoute:
    AuthenticatedAdminCourseAgentsConversationRoute,
  AuthenticatedAdminCourseAgentsModelRoute:
    AuthenticatedAdminCourseAgentsModelRoute,
  AuthenticatedAdminCourseAgentsStateMachineRoute:
    AuthenticatedAdminCourseAgentsStateMachineRoute,
  AuthenticatedAdminKnowledgeKbIdRoute: AuthenticatedAdminKnowledgeKbIdRoute,
  AuthenticatedSaasadminAgentsAgentIdRoute:
    AuthenticatedSaasadminAgentsAgentIdRoute,
  AuthenticatedSaasadminKnowledgeKbIdRoute:
    AuthenticatedSaasadminKnowledgeKbIdRoute,
  AuthenticatedAdminCourseAgentsIndexRoute:
    AuthenticatedAdminCourseAgentsIndexRoute,
  AuthenticatedAdminKnowledgeIndexRoute: AuthenticatedAdminKnowledgeIndexRoute,
  AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  AuthenticatedAdminModelsIndexRoute: AuthenticatedAdminModelsIndexRoute,
  AuthenticatedAdminUsageIndexRoute: AuthenticatedAdminUsageIndexRoute,
  AuthenticatedSaasadminAgentsIndexRoute:
    AuthenticatedSaasadminAgentsIndexRoute,
  AuthenticatedSaasadminAuditIndexRoute: AuthenticatedSaasadminAuditIndexRoute,
  AuthenticatedSaasadminKnowledgeIndexRoute:
    AuthenticatedSaasadminKnowledgeIndexRoute,
  AuthenticatedSaasadminModelsIndexRoute:
    AuthenticatedSaasadminModelsIndexRoute,
  AuthenticatedSaasadminTenantsIndexRoute:
    AuthenticatedSaasadminTenantsIndexRoute,
  AuthenticatedSaasadminUsageIndexRoute: AuthenticatedSaasadminUsageIndexRoute,
  AuthenticatedSaasadminUsersIndexRoute: AuthenticatedSaasadminUsersIndexRoute,
  AuthenticatedAdminCourseAgentsLeadsLeadIdRoute:
    AuthenticatedAdminCourseAgentsLeadsLeadIdRoute,
  AuthenticatedAdminCourseAgentsLeadsIndexRoute:
    AuthenticatedAdminCourseAgentsLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  JoinSlugRoute: JoinSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
